#!/bin/bash
#systemctl disable firewalld --now
#setenforce 0
#sed -i "/SELINUX/s/enforcing/permissive/" /etc/selinux/config
#hostnamectl set-hostname zabbix-agent
#bash
#yum -y install httpd mariadb-server mariadb php php-mysql php-gd libjpeg* php-ldap php-odbc php-pear php-xml php-xmlrpc php-mhash
#sed -i "/#ServerName/s/#ServerName/ServerName/" /etc/httpd/conf/httpd.conf
#sed -i "/DirectoryIndex/c DirectoryIndex index.php index.html" /etc/httpd/conf/httpd.conf
#sed -i "/;date.timezone/c date.timezone = PRC" /etc/php.ini
#systemctl enable httpd --now
#systemctl enable mariadb.service --now
#netstat -anpt |grep 80
#netstat -anpt | grep 3306
#mysql_secure_installation
#echo "<?php
#      phpinfo();
#      ?>" > /var/www/html/index.php
#mysql -uroot -p123 -e "create database zabbix character set utf8 collate utf8_bin"
#mysql -uroot -p123 -e "grant all on zabbix.* to zabbix@'%' identified by 'admin123'"
#mysql -uroot -p123 -e "flush privileges"

rpm -ivh http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm 
yum -y install  zabbix-agent
#yum -y install  zabbix-web-mysql
#zcat /usr/share/doc/zabbix-server-mysql-4.0.32/create.sql.gz | mysql -uzabbix -padmin123 zabbix
#sed -i "s/graphfont/kaiti/g" /usr/share/zabbix/include/defines.inc.php
systemctl enable zabbix-server --now
sed -i "98c Server=192.168.224.14" /etc/zabbix/zabbix_agentd.conf
sed -i "/ServerActive/c ServerActive=192.168.224.14" /etc/zabbix/zabbix_agentd.conf
systemctl enable zabbix-agent.service
systemctl restart zabbix-agent.service
netstat -antp |grep zabbix



